### ISSUE TITLE
Unable to authenticate via the eIDAS proxy service of the country "IT"

### ISSUE THREAD

**Issue by gabriele-costa** [AgID/eidas-italian-node#15]
Dalla pagina web
[https://europa.eu/europass/eportfolio/api/europass-auth/authenticate?redirect_uri=https://europa.eu/europass/eportfolio/screen/mfa?lang=it](https://europa.eu/europass/eportfolio/api/europass-auth/authenticate?redirect_uri=https://europa.eu/europass/eportfolio/screen/mfa?lang=it)

Selezionando l'opzione `Sign in with your eID` e successivamente selezionando la voce corrispondente all'Italia si ottiene l'errore

`Unable to authenticate via the eIDAS proxy service of the country "IT".`

**Comment by zabuza88** [comment]
è così da settimane

**Comment by rawmain** [comment]
Ciao @gabriele-costa e @zabuza88 

Sono in corso nuovi controlli ed il problema parrebbe risolto = ulteriori dettagli + screenshot in commento a precedente issue #12 

[https://github.com/AgID/eidas-italian-node/issues/12#issuecomment-1881691490](https://github.com/AgID/eidas-italian-node/issues/12#issuecomment-1881691490)

Potete ricontrollare & confermare (o smentire) se anche voi riscontriate il rientro per le vostre casistiche? Grazie.

**Comment by gabriele-costa** [comment]
Il comportamento è cambiato, ma un problema rimane. Ora viene fatto fatto correttamente il redirect al portale SPiD, effettuo l'autenticazione con il mio ID provider, e viene mostrata la richiesta di autorizzazione di accesso ai dati personali. Quando però procedo e viene effettuato il redirect all'indietro verso il servizio ottengo questo messaggio di errore.
```
You are currently logged in as user 'n------n' and cannot use an authentication factor registered to user 'v------2'
```
(ho nascosto parte degli user id con il simbolo -)

Ovviamente quando faccio l'autenticazione non sono già autenticato al sistema (es. usando una password o altro).

**Comment by rawmain** [comment]
Ciao @gabriele-costa 

> Ora viene fatto fatto correttamente il redirect al portale SPiD, effettuo l'autenticazione con il mio ID provider, e viene mostrata la richiesta di autorizzazione di accesso ai dati personali. 

Infatti ora non fallisce più la ProxyServiceRequest. Grazie anche per la tua conferma.

.
> Quando però procedo e viene effettuato il redirect all'indietro verso il servizio ottengo questo messaggio di errore.
> 
> ```
> You are currently logged in as user 'n------n' and cannot use an authentication factor registered to user 'v------2'
> ```

Questa situazione non deriva però da problemi lato nodo eIDAS ITA / gestore SPID. 

Ho fatto alcune prove, onde ricreare/verificare la tua situazione & appurare se fossero eventualmente variate le policy di creazione/gestione UID EU Login rispetto a quanto noto (_[cfr. e.g. questo thread su Forum Italia](https://forum.italia.it/t/id-eidas-diverso-tra-cie-e-spid/26022)_).

Tale avviso si riscontra qualora lato piattaforma EU Login non venga rilevata o validata un'associazione di link/reconciliation tra l'UID dell'account EU Login registrato con email+password (`UID n*******`) e l'UID Federated ID (`UID v*******`) associato all'attributo identificativo trasmesso dall'IdP.

.
In tal caso la piattaforma EU Login li vede comunque come 2 account distinti/scollegati, seppur associati al medesimo indirizzo email, restituendo un avviso KO quando usi il flusso di **signin Email o username n******* **EU Login + verifica tramite eID Authentication** (_cioè quello in immagine sotto_). 

![EID_00_signinUIDn](https://github.com/AgID/eidas-italian-node/assets/18743336/26ea9c54-7247-483a-9eb6-898efb4145d1)

Se usi invece l'altro flusso di **signin diretto / Different E-mail Address via eID**, il sistema processerà correttamente l'autenticazione per l'account v******* = vedrai tale UID (_e non n*******_) indicato come Username / Unique Identifier nel pannello **My Account \ My account details** di EU Login.

.
Puoi controllare / reimpostare la situazione link/reconciliation da una nuova sessione senza precedenti cookie/cache (_e.g. via modalità in incognito_) :

- Usando flusso signin **signin Email o username n******* **+ password** , selezionando il verification method opportuno = password, se non hai impostato MFA per tutti gli accessi, oppure altro da te impostato/usato (_EU Mobile app pin/QR, Phone/SMS, Token, etc._) ovviamente diverso da eID Auth.

- Una volta autenticato come n******* (_ved. info username/account in My Account \ My account details_), andando in **My Account \ Manage my eIDs** = se vedi anche l'opzione Delete an eID, rimuovi obv prima gli ID registrati, quindi clicca su Link my eID e segui le istruzioni a schermo per associare il tuo account SPID.

- Verificando che in My Account \ My account details risulti associato solo un Federated ID STORK:IT/EU/************** - con ovviamente al posto dei 10 asterischi l'identificativo trasmesso dal gestore SPID, che hai usato nella procedura di link/reconcliation.

.
Queste sono e.g. le info di reconciliation / federated ID per un UID Account n******* EU Login correttamente collegato agli UID v******* di 2 account SPID (_nello specifico Poste e Sielte_) .

![EID_00_FederatedIDs](https://github.com/AgID/eidas-italian-node/assets/18743336/6233e3ba-65ab-4b83-b652-63a7bde1c248)

A conferma della corretta reconciliation, l'autenticazione - indipendentemente da flusso/metodi selezionati per signin - porta sempre ad un'unica area di lavoro associata all'account n******* (cfr. info in My Account details).

.
Fammi sapere se così risolvi.

**Comment by gabriele-costa** [comment]
Caro @rawmain,

intanto grazie della risposta dettagliata e utilissima. Ho effettivamente controlalto e cancellato i cookie di sessione e il problema si è risolto definitivamente.

Grazie ancora per il supporto
